name: 01- Building Blocks
on: push
jobs:
  echo-hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World"
  echo-goodbye-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Success Step"
        run: | #vertical line or pipe is required to define multiline commands
          echo "This job will be a success"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye"
          