name: 01- Building Blocks  # workflow name
on: workflow_dispatch # trigger point
jobs: # jobs which is an object. Every keys of a job is a job-name. Value of each key is the job definition
  echo-hello-job:
    runs-on: ubuntu-latest #platform in which the job should run
    steps: # steps is an array of objects.
      - name: Say Hello #step name
        run: echo "Hello World" #command to be executed on the platform
  echo-goodbye-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Success Step"
        run: | #vertical line or pipe is required to define multiline commands
          echo "This job will be a success"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye"
          