name: 02 - Workflow Events
on:
    # - push
    # - pull_request
    #- schedule #cron-job
    - workflow_dispatch # manual trigger from the Github Actions UI in Github website (Run Workflow)
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo ${{ github.event_name }}
