name: 02.01 Workflow Event On Trigger as object
on:
    # push:
    # pull_request:
    workflow_dispatch:
    # schedule:
    #     - cron: '0 0 1 1 *'

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World"
              name: Workflow triggered
