name: 06 - Contexts
on:
  # push:
  workflow_dispatch:
    inputs:
      debug:
        default: false
        type: boolean
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
env:
  MY_WORKFLOW_VAR: workflow
  MY_OVERWRITTEN_VAR: workflow
jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display info
              run: |
                echo "Event name: ${{ github.event }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run Id: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number }}"
            
            - name: Retrieve Variable
              run: echo "${{ vars.MY_VAR }}" # you can define repository variables at github settings under https://github.com/<user>/<repo-name>/settings/variables/actions
            
            - name: Print Env Variables
              env:
                MY_OVERWRITTEN_VAR: step # This value of step will only be available in the step Print Env Variables outside them will be the old value
                
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Workflow env: ${{ env.MY_OVERWRITTEN_VAR }}"
            
            - name: Yet another Env Variables
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Workflow env: ${{ env.MY_OVERWRITTEN_VAR }}"

