name: "10 - Controlling the Execution Flow"
# Jobs always runs in parallel. If a job depends on other then we need to add the needs key at the job level and put the dependent jobs in an array
# If there are 4 jobs for eg: Job A, Job B, Job C and Job D, and Job C is dependent on Job A and B, then Job C will not be executed unless Job A and Job B is completed successfully.
# If either A or B fails, C will be skipped. Job D runs in parallel with A and B, and is not affected by their success/failure.
on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                default: false

jobs:

    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and build
              run: echo "Linting and building project"
    

    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Running unit tests
              run: echo "Running tests..."
            
            - name: Failing tests
              if: inputs.pass-unit-tests == false
              run: exit 1
    

    deploy-non-prod:
        runs-on: ubuntu-latest
        needs: 
            - lint-build
            - unit-tests
        steps:
            - name: "Deploying to non prod"
              run: echo "Deploying to nonprod..."

    
    e2e-tests:
        runs-on: ubuntu-latest
        needs: 
            - deploy-non-prod
        steps:
            - name: E2E tests
              run: echo "Running E2E tests"


    
    load-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-non-prod
        steps:
            - name: Running load tests
              run: echo "Running load tests"
    
    
    deploy-prod:
        runs-on: ubuntu-latest
        needs:
            - e2e-tests
            - load-tests
        steps:
            - name: Deploying to prod
              run: echo "Deploying to prod..."